/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutingExpressionsRouteImport } from './routes/routing-expressions'
import { Route as RoutingExpressionsIndexRouteImport } from './routes/routing-expressions.index'
import { Route as RoutingExpressionsCreateRouteImport } from './routes/routing-expressions.create'
import { Route as RoutingExpressionsTestRouteImport } from './routes/routing-expressions.test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutingExpressionsRoute = RoutingExpressionsRouteImport.update({
  id: '/routing-expressions',
  path: '/routing-expressions',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutingExpressionsIndexRoute = RoutingExpressionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoutingExpressionsRoute,
} as any)
const RoutingExpressionsCreateRoute =
  RoutingExpressionsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => RoutingExpressionsRoute,
  } as any)
const RoutingExpressionsTestRoute = RoutingExpressionsTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => RoutingExpressionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/routing-expressions': typeof RoutingExpressionsRouteWithChildren
  '/routing-expressions/create': typeof RoutingExpressionsCreateRoute
  '/routing-expressions/test': typeof RoutingExpressionsTestRoute
  '/routing-expressions/': typeof RoutingExpressionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/routing-expressions/create': typeof RoutingExpressionsCreateRoute
  '/routing-expressions/test': typeof RoutingExpressionsTestRoute
  '/routing-expressions': typeof RoutingExpressionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/routing-expressions': typeof RoutingExpressionsRouteWithChildren
  '/routing-expressions/create': typeof RoutingExpressionsCreateRoute
  '/routing-expressions/test': typeof RoutingExpressionsTestRoute
  '/routing-expressions/': typeof RoutingExpressionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/routing-expressions'
    | '/routing-expressions/create'
    | '/routing-expressions/test'
    | '/routing-expressions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/routing-expressions/create'
    | '/routing-expressions/test'
    | '/routing-expressions'
  id:
    | '__root__'
    | '/'
    | '/routing-expressions'
    | '/routing-expressions/create'
    | '/routing-expressions/test'
    | '/routing-expressions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoutingExpressionsRoute: typeof RoutingExpressionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routing-expressions': {
      id: '/routing-expressions'
      path: '/routing-expressions'
      fullPath: '/routing-expressions'
      preLoaderRoute: typeof RoutingExpressionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routing-expressions/': {
      id: '/routing-expressions/'
      path: '/'
      fullPath: '/routing-expressions/'
      preLoaderRoute: typeof RoutingExpressionsIndexRouteImport
      parentRoute: typeof RoutingExpressionsRoute
    }
    '/routing-expressions/create': {
      id: '/routing-expressions/create'
      path: '/create'
      fullPath: '/routing-expressions/create'
      preLoaderRoute: typeof RoutingExpressionsCreateRouteImport
      parentRoute: typeof RoutingExpressionsRoute
    }
    '/routing-expressions/test': {
      id: '/routing-expressions/test'
      path: '/test'
      fullPath: '/routing-expressions/test'
      preLoaderRoute: typeof RoutingExpressionsTestRouteImport
      parentRoute: typeof RoutingExpressionsRoute
    }
  }
}

interface RoutingExpressionsRouteChildren {
  RoutingExpressionsCreateRoute: typeof RoutingExpressionsCreateRoute
  RoutingExpressionsTestRoute: typeof RoutingExpressionsTestRoute
  RoutingExpressionsIndexRoute: typeof RoutingExpressionsIndexRoute
}

const RoutingExpressionsRouteChildren: RoutingExpressionsRouteChildren = {
  RoutingExpressionsCreateRoute: RoutingExpressionsCreateRoute,
  RoutingExpressionsTestRoute: RoutingExpressionsTestRoute,
  RoutingExpressionsIndexRoute: RoutingExpressionsIndexRoute,
}

const RoutingExpressionsRouteWithChildren =
  RoutingExpressionsRoute._addFileChildren(RoutingExpressionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoutingExpressionsRoute: RoutingExpressionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
